#define MAXN  1000
#include <iostream>
using std::cout;

void purgatory(){
	TFile * file = TFile::Open("VertexRestorer.root");
	int bin_e = 50;
	float max_e = 1.;
	TCanvas * c1 = new TCanvas("c1", "Data-MC",0,0,500,500);
//	c1->Divide(2,1);
	TH1F * kaons = new TH1F("kaons", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * taons = new TH1F("taons", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * hyperons = new TH1F("hyperons", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * sbaryons = new TH1F("sbaryons", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * chadrons = new TH1F("chadrons", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * bhadrons = new TH1F("bhadrons", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * gamma = new TH1F("gamma", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * gluon = new TH1F("gluon", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * others = new TH1F("others", "Offset;#epsilon", bin_e,0.0,max_e);
	TH1F * total = new TH1F("total", "Offset;#epsilon", bin_e,0.0,max_e);
	Purgatory->Project("kaons","purgatoryOffset", "purgatoryVtxHits > 3 && purgatoryParent > 300 && purgatoryParent < 400");
	Purgatory->Project("taons","purgatoryOffset", "purgatoryVtxHits > 3 && purgatoryParent == 15");
	Purgatory->Project("sbaryons","purgatoryOffset", "purgatoryVtxHits > 3 && ((purgatoryParent > 3000 && purgatoryParent < 4000))");
	Purgatory->Project("chadrons","purgatoryOffset", "purgatoryVtxHits > 3 && ((purgatoryParent > 4000 && purgatoryParent < 5000) || (purgatoryParent > 400 && purgatoryParent < 500))");
	Purgatory->Project("bhadrons","purgatoryOffset", "purgatoryVtxHits > 3 && ((purgatoryParent > 5000 && purgatoryParent < 6000) || (purgatoryParent > 500 && purgatoryParent < 600))");
	Purgatory->Project("gamma","purgatoryOffset", "purgatoryVtxHits > 3 && purgatoryParent == 22");
	Purgatory->Project("gluon","purgatoryOffset", "purgatoryVtxHits > 3 && (purgatoryParent == 92 || purgatoryParent == 94 || purgatoryParent == -50000)");
	Purgatory->Project("total","purgatoryOffset", "purgatoryVtxHits > 3");
	c1->cd(1);
	kaons->SetLineColor(kYellow+1);
	kaons->SetFillColor(kYellow);
	kaons->SetLineWidth(3);
	taons->SetLineColor(kOrange+1);
	taons->SetFillColor(kOrange);
	taons->SetLineWidth(3);
	chadrons->SetLineColor(kCyan+1);
	chadrons->SetFillColor(kCyan);
	chadrons->SetLineWidth(3);
	bhadrons->SetLineColor(kBlue+1);
	bhadrons->SetFillColor(kBlue);
	bhadrons->SetLineWidth(3);
	sbaryons->SetLineColor(kGreen+1);
	sbaryons->SetFillColor(kGreen);
	sbaryons->SetLineWidth(3);
	gamma->SetLineColor(kRed+1);
	gamma->SetFillColor(kRed);
	gamma->SetLineWidth(3);
	gluon->SetLineColor(kMagenta+1);
	gluon->SetFillColor(kMagenta);
	gluon->SetLineWidth(3);
	total->SetLineColor(kGray+1);
	total->SetFillColor(kGray);
	total->SetLineWidth(3);
	THStack * stackp = new THStack("satck","Offset;#epsilon");
	total->Draw();
	stackp->Add(gamma);
	stackp->Add(gluon);
	stackp->Add(sbaryons);
	stackp->Add(chadrons);
	stackp->Add(bhadrons);
	stackp->Add(kaons);
	stackp->Add(taons);
	stackp->Draw("same");
	TLegend *legendMean = new TLegend(0.17,0.7,0.5,0.92,NULL,"brNDC");
	legendMean->SetFillColor(kWhite);
	legendMean->SetBorderSize(0);
	legendMean->AddEntry(gamma,"photons","fp");
	legendMean->AddEntry(gluon,"gluons(PDG 92, 94) + #pi #to #mu #bar{#nu}","fp");
	legendMean->AddEntry(taons,"taus","fp");
	legendMean->AddEntry(kaons,"kaons","fp");
	legendMean->AddEntry(sbaryons,"s-baryons","fp");
	legendMean->AddEntry(chadrons,"c-hadrons","fp");
	legendMean->AddEntry(bhadrons,"b-hadrons","fp");
	legendMean->AddEntry(total,"others","fp");
	legendMean->Draw();
	gPad->Modified();
	c1->cd(2);
	std::cout << "Gammas " << kaons->Integral() << "\n";
	//kaons->Draw();
	//sbaryons->Draw();
	//gamma->Draw();
}
